# Generated by Django 6.0.6 on 2026-06-24 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerRackSensorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rack_identifier', models.CharField(db_index=True, max_length=100)),
                ('temperature_celsius', models.FloatField()),
                ('humidity_percentage', models.FloatField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ThermalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alert_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('sensor_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.serverracksensorlog')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
